### ISSUE TITLE
Can't set the keyboard backlight timeout on AC using stop_timeout

### ISSUE THREAD

**Issue by anthon38** [dell/libsmbios#105]
Hello, 
the laptop is an Inspiron 15 7510. The issue I'm running into is pretty much this: https://github.com/dell/libsmbios/issues/48
meaning I can't set the keyboard backlight on AC using `/sys/class/leds/dell::kbd_backlight/stop_timeout`, except:
- I can set the value in the BIOS
- I can set the value using Dell Command configure (`/opt/dell/dcc/cctk --kbdbacklighttimeoutac=15m` for example)
- I can't set it using` smbios-keyboard-ctl --set-timeout-ac=15m`. This returns: 

> Traceback (most recent call last):
  File "/usr/bin/smbios-keyboard-ctl", line 713, in <module>
    sys.exit( main() )
  File "/usr/bin/smbios-keyboard-ctl", line 680, in main
    raise RunTimeKeyboardErr("This system doesn't support AC timeout" )
__main__.RunTimeKeyboardErr: This system doesn't support AC timeout

- The token 0x451 is absent (`smbios-token-ctl -i 0x451` returns nothing)

As per this comment https://github.com/dell/libsmbios/issues/48#issuecomment-391142780 
>  If you can set it from there then we are looking at a bug in the implementation of detecting AC support is available.

I'm reporting this here. 
I also don't know if it's related but while fiddling with this, I've been able to use the mouse as a start_trigger (only on battery, wasn't working at first; this never worked on ac), but now it won't work again... If it's completely unrelated, please let me know so I can investigate further this different issue.

**Comment by Theluga** [comment]
I want to add that the inspiron 13 7359 has a similar bug.

Setting the time out for the keyboard backlight worked for AC and Battery. 

After some bios updates some years ago it stopped working. It only time-out now on battery. 

But I cannot set it in bios. I can set on the OS but it is ignored when on AC.

Could you also help me?

I would not care if it was a quirky patch on the linux kernel or a new bios update.

Should I open a new issue? 

I don't know if this is the right place to post this error.

Thank you!
