### ISSUE TITLE
Fedora 40 on Lenovo T14 gen5 error token not found

### ISSUE THREAD

**Issue by pierrehenrymuller** [dell/libsmbios#146]
Hi,
When I launch `smbios-battery-ctl --get-charging-cfg` on a Lenovo Thinkpad T14 gen5, I have this error in Python : 
```
Traceback (most recent call last):
  File "/sbin/smbios-battery-ctl", line 275, in <module>
    sys.exit( main() )
              ^^^^^^
  File "/sbin/smbios-battery-ctl", line 241, in main
    print_primary_battery_cfg()
  File "/sbin/smbios-battery-ctl", line 190, in print_primary_battery_cfg
    mode = get_charging_mode()
           ^^^^^^^^^^^^^^^^^^^
  File "/sbin/smbios-battery-ctl", line 140, in get_charging_mode
    active = table[mode.value].isActive()
             ~~~~~^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/libsmbios_c/trace_decorator.py", line 103, in trace
    result = func(*args, **kw)
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/libsmbios_c/smbios_token.py", line 145, in __getitem__
    raise IndexError(_("SMBIOS Token ID 0x%04x not found") % id )
IndexError: SMBIOS Token ID 0x0341 not found
```

The Fedora is up to date, firmware too : 
```
fwupdmgr update                                                                                             1 ⨯
Devices with no available firmware updates: 
 • Intel Management Engine
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • ELAN0676:00 04F3:3195
 • Integrated Camera
Devices with the latest available firmware version:
 • System Firmware
 • MZVL8512HDLU-00BLL
 • UEFI dbx
```

On other T14 gen3 or older T14 they works fine on same version of Fedora.
Is there an unsupported device or a bug?
Thanks

**Comment by sergiomb2** [comment]
other report in https://bugzilla.redhat.com/show_bug.cgi?id=2307490   

 SMBIOS Token ID 0x0346 not found

**Comment by redneb** [comment]
I am seeing the same error (`SMBIOS Token ID 0x0341 not found`) on my Dell XPS 15 9520. Interestingly enough, this used to work until a few weeks ago. I am guessing some software upgrade (maybe the kernel?) must have broken it.

**Comment by nbennke** [comment]
I also get `SMBIOS Token ID 0x0341 not found` on my Dell Precision M6600, running with Debian 12. Any news on this issue?
